import { Hind_Siliguri } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const hind_Shiliguri = Hind_Siliguri({
  subsets: ["latin", "bengali"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hind_Shiliguri.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#E1E8E1]">
        <Navbar></Navbar>
        <main>{children}</main>
      </body>
    </html>
  );
}
